PCAT_PACKAGE:=luci-app-photonicat2-cpu
PCAT_TITLE:=Photonicat 2 CPU power saving
PCAT_VIEW:=cpu
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
