PCAT_PACKAGE:=luci-app-photonicat2-power
PCAT_TITLE:=Photonicat 2 power policies
PCAT_VIEW:=policy
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
