PCAT_PACKAGE:=luci-app-photonicat2-battery
PCAT_TITLE:=Photonicat 2 battery statistics
PCAT_VIEW:=battery
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
