PCAT_PACKAGE:=luci-app-photonicat2-led
PCAT_TITLE:=Photonicat 2 status LED control
PCAT_VIEW:=led
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
