PCAT_PACKAGE:=luci-app-photonicat2-fan
PCAT_TITLE:=Photonicat 2 smart fan
PCAT_VIEW:=fan
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
