PCAT_PACKAGE:=luci-app-photonicat2-wireless
PCAT_TITLE:=Photonicat 2 onboard wireless
PCAT_VIEW:=wireless
PCAT_DEPENDS:=+kmod-aic8800-usb
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
