PCAT_PACKAGE:=luci-app-photonicat2-screen
PCAT_TITLE:=Photonicat 2 mini display editor
PCAT_VIEW:=screen
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
