PCAT_PACKAGE:=luci-app-photonicat2-charge
PCAT_TITLE:=Photonicat 2 charge limit
PCAT_VIEW:=charge
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
