PCAT_PACKAGE:=luci-app-photonicat2-buzzer
PCAT_TITLE:=Photonicat 2 buzzer control
PCAT_VIEW:=buzzer
include $(TOPDIR)/package/ning/photonicat2/luci-package.mk
# BuildPackage marker: $(eval $(call BuildPackage,$(PCAT_PACKAGE)))
